config/routes.rb
Rails.application.routes.draw do
  root to: "portfolios#index"

  get 'about/index', to: 'abouts#index'
  get 'contact/index', to: 'contacts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  def index
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/abouts/index.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>About｜風景写真家「SNAPPERS」</title>
<link href="https://fonts.googleapis.com/css?family=Bitter:400,700" rel="stylesheet">
<link href="css/about_style.css" rel="stylesheet">
</head>
<body id="about">
  
  
  <!-- wrap始まり -->
  <div id="wrap">
    <div class="content">
      <div class="main-center">
        <h1>About</h1>
        <p>SNAPPERS代表、山田太郎のプロフィールや経歴の紹介ページです。</p>
        <section class="profile clearfix">
          <div class="profile-txt">
            <h2 class="icon">Profile</h2>
            <p><span>SNAPPERS 代表：山田 太郎</span><br>アナログ、デジタルを問わず、トイカメラやポラロイド、ビデオカメラに至るまで、あらゆるカメラに夢中になって遊んでいるうちに自然とカメラマンとしての道を志すようになる。<br>大学卒業後、有名カメラマンのアシスタントを経て渡米。世界各国を放浪しながら撮影をする中で、現在のアウトドアカメラマンとしてのスタイルを確立する。2016年に帰国し、「SNAPPERS」を設立。<br>現在は、雑誌の表紙やカタログの撮影を中心に、映像作品などにもカメラマンとして参加するなど幅広く活躍している。</p>
          </div>
          <img src="images/about-profile.png" alt="山田太郎プロフィール画像" class="profile-image">
        </section>
        <section class="career">
          <h2 class="icon">Career and Job history</h2>
          <table>
            <tr>
              <th>1994年3月</th>
              <td>丸三角芸術大学写真科 卒業　服部写真研究所に入社、服部英明氏に師事</td>
            </tr>
            <tr>
              <th>2002年3月</th>
              <td>服部写真研究所を退社し渡米、世界各国を放浪しながら撮影を続ける</td>
            </tr>
            <tr>
              <th>2012年8月</th>
              <td>イタリア・ミラノで開催されたコンクールにて、審査員特別賞受賞</td>
            </tr>
            <tr>
              <th>2016年1月</th>
              <td>帰国し「SNAPPERS」を設立</td>
            </tr>
            <tr>
              <th>2016年4月</th>
              <td>Aichi Musiumにて初の写真展「Snap!Snap!」を開催</td>
            </tr>
          </table>
        </section>
      </div>
    </div>
  </div>
  <!-- wrap終わり -->
  
  
</body>
</html>

app/views/contacts/index.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Contact｜風景写真家「SNAPPERS」</title>
<link href="https://fonts.googleapis.com/css?family=Bitter:400,700" rel="stylesheet">
<link href="css/contact_style.css" rel="stylesheet">
</head>
<body id="contact">
  
  
  <!-- wrap始まり -->
  <div id="wrap">
    <div class="content">
      <div class="main-center">
        <h1>Contact</h1>
        <p>SNAPPERSへのアクセス方法、お問い合わせ、撮影のご依頼フォームのページです。お気軽にお問い合わせください。</p>
        <section class="access clearfix">
          <h2 class="icon">Access</h2>
          <table>
            <tr>
              <th>所在地住所</th>
              <td>〒123-4567 静岡県伊東市伊豆高原○△☆-12</td>
            </tr>
            <tr>
              <th>電話番号</th>
              <td>012-3456-7890</td>
            </tr>
            <tr>
              <th>電車でのアクセス</th>
              <td>伊豆急行「伊豆高原」駅より徒歩15分</td>
            </tr>
            <tr>
              <th>お車でのアクセス</th>
              <td>伊豆山I.Cより国道135号線経由で50分</td>
            </tr>
          </table>
          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3273.1425016216936!2d139.1061616154649!3d34.87776778122144!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6019dcd319ce2d9f%3A0xbc111be9ad0e0569!2z5LyK6LGG6auY5Y6f!5e0!3m2!1sja!2sjp!4v1494779533095" width="460" height="220" frameborder="0" style="border:0" allowfullscreen></iframe>
        </section>
        <section>
          <h2 class="icon">Contact form</h2>
          <div class="form">
            <form>
              <dl>
                <dt><span class="required">お名前</span></dt>
                <dd><input type="text" name="name" class="name" required></dd>
                <dt><span class="required">メールアドレス</span></dt>
                <dd><input type="email" name="email" class="email" required></dd>
                <dt>お電話番号</dt>
                <dd><input type="tel" name="tel" class="tel"></dd>
                <dt>お問合せ種別</dt>
                <dd>
                  <select name="type" class="type">
                    <option value="撮影のご依頼">撮影のご依頼</option>
                    <option value="講演・各種メディア出演のご依頼">講演・各種メディア出演のご依頼</option>
                    <option value="その他お問い合わせ">その他お問い合わせ</option>
                  </select>
                </dd>
                <dt>ご希望のご連絡方法</dt>
                <dd>
                  <input type="radio" name="contact" value="Eメール">Eメール
                  <input type="radio" name="contact" value="お電話">お電話
                </dd>
                <dt>メッセージ</dt>
                <dd><textarea name="message" class="message"></textarea></dd>
              </dl>
              <button type="submit">送信</button>
            </form>
            <div class="attention">
              <p>※ 「<span class="required"></span>」の付いている項目は必須項目です。<br>※メッセージ送信後、48時間以内に担当者よりご連絡いたします。</p>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
  <!-- wrap終わり -->
  
  
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- header始まり -->
  <header>
    <div class="logo">
      <a href="index.html"><img src="images/logo.png" alt="SNAPPERS"></a>
    </div>
    <nav>
      <ul class="global-nav">
        <li><%= link_to "Portfolio", root_path %></li>
        <li><%= link_to "About", about_index_path %></li>
        <li><%= link_to "Contact", contact_index_path %></li>
      </ul>
    </nav>
  </header>
  <!-- header終わり -->

    <%= yield %>

      <!-- footer始まり -->
  <footer>
    <small>(C)2017 Hattori-studio.</small>
  </footer>
  <!-- footer終わり -->

  </body>
</html>

app/views/portfolios/index.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Portfolio｜風景写真家「SNAPPERS」</title>
<link href="https://fonts.googleapis.com/css?family=Bitter:400,700" rel="stylesheet">
<link href="css/style.css" rel="stylesheet">
</head>
<body id="portfolio">
  
  
  <!-- wrap始まり -->
  <div id="wrap" class="clearfix">
    <div class="content">
      <div class="main">
        <h1>Portfolio</h1>
        <p>これまでに撮影した写真や映像作品を掲載しています。</p>
        <section>
          <h2><a href="photograph.html"><img src="images/portfolio-photo.jpg" alt="PHOTOGRAPH"></a></h2>
          <p>SNAPPERSでは「街-City」「海-Beach」「森-Forest」の3つの場所で、様々な角度から「人の気配」を撮影します。人が写っていない写真の中にも確かにそこにある、人の気配を感じとっていただけると嬉しいです。<a href="photograph.html">詳しくみる ≫</a></p>
        </section>
        <section>
          <h2><a href="video.html" ><img src="#" alt="VIDEO"></a></h2>
          <p>SNAPPERSでは映像作品も撮影しております。ドローンでの空撮やアクションカメラを使用した、屋外でのダイナミックな映像を得意としています。またショートフィルムを映画祭などで上映することもあります。<a href="video.html">詳しくみる ≫</a></p>
        </section>
      </div>
      <aside class="sidebar">
        <section>
          <h2>Photograph</h2>
          <ul>
            <li><a href="photograph.html#city">街-City</a></li>
            <li><a href="photograph.html#beach">海-Beach</a></li>
            <li><a href="photograph.html#forest">森-Forest</a></li>
          </ul>
        </section>
        <section>
          <h2>Video</h2>
          <ul>
            <li><a href="video.html#movie">Movie</a></li>
            <li><a href="video.html#short-film">Short film</a></li>
          </ul>
        </section>
      </aside>
    </div>
  </div>
  <!-- wrap終わり -->
  
  
</body>
</html>